name: Publish release to production environment

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build new image and push
        run: |
          make \
            pull-image \
            build-docker-cached \
            push-image
        env:
          LATEST_TAG: latest
          NEXT_PUBLIC_APP_UAL_API_PROTOCOL: 'https'
          NEXT_PUBLIC_APP_UAL_API_HOST: ${{ secrets.NEXT_PUBLIC_APP_UAL_API_HOST }}
          NEXT_PUBLIC_APP_UAL_API_PORT: '443'
          NEXT_PUBLIC_EDENSMARTPROXY_CONTRACT: edensmartprx
          NEXT_PUBLIC_MYVOTEEOSDAO_CONTRACT: myvoteeosdao
          RELEASE_TAG: ${{ steps.tag.outputs.tag }}
          VERSION: ${{ steps.tag.outputs.tag }}

      - name: Build kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          VERSION: ${{ steps.tag.outputs.tag }}

      - name: Setup and deploy kubernetes environment
        uses: steebchen/kubectl@v1.1.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: edenproxy
          K8S_BUILD_DIR: build_k8s
        with:
          args: version && make deploy-kubernetes

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
