name: Publish release to production environment

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build new image and push
        run: |
          make \
            build-docker \
            push-image
        env:
          LATEST_TAG: latest
          NEXT_PUBLIC_UAL_APP_NAME: 'edensmartprx'
          NEXT_PUBLIC_UAL_API_PROTOCOL: 'https'
          NEXT_PUBLIC_UAL_API_HOST: ${{ secrets.NEXT_PUBLIC_UAL_API_HOST }}
          NEXT_PUBLIC_UAL_API_PORT: '443'
          NEXT_PUBLIC_UAL_CHAIN_ID: ${{ secrets.NEXT_PUBLIC_UAL_CHAIN_ID }}
          NEXT_PUBLIC_AA_API_HOST: ${{ secrets.NEXT_PUBLIC_AA_API_HOST }}
          NEXT_PUBLIC_GENESISEDEN_CONTRACT: genesis.eden
          NEXT_PUBLIC_EDENSMARTPROXY_CONTRACT: edensmartprx
          NEXT_PUBLIC_MYVOTEEOSDAO_CONTRACT: myvoteeosdao
          NEXT_PUBLIC_PRODUCERS_INFO_API_URL: https://graphql-eos.antelope.tools/api/rest/get-producers-info
          RELEASE_TAG: ${{ steps.tag.outputs.tag }}

      - name: Build voter image and push
        run: |
          make \
            build-docker-voter \
            push-image-voter

      - name: Build kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          LATEST_TAG: latest
          EOS_API_ENDPOINT: 'https://api.eosn.io'
          EOS_API_CHAIN_ID: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906'
          EOS_VOTER_ACCOUNT: 'edensmartprx'
          EOS_VOTER_PERMISSION: 'proxyvote'
          EOS_VOTER_PRIVATE_KEY: ${{ secrets.EOS_VOTER_PRIVATE_KEY }}
          EOS_PROXY_ACCOUNT: 'edensmartprx'

      - name: Setup and deploy kubernetes environment
        uses: steebchen/kubectl@v1.1.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: edenproxy
          K8S_BUILD_DIR: build_k8s
        with:
          args: version && make deploy-kubernetes

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
